### PR TITLE
Moved EventCategory definition from review-database

### LINKED ISSUE #15: Move EventCategory definition from review-database
Related: https://github.com/petabi/review-database/issues/304

- [x] Move EventCategory definition from review-protocol crate
- [x] Remove the HttpThreat member from the EventCategory

### PR DESCRIPTION
**Pull request by syncpark**
Close #15 

- Moved `EventCategory` definition from review-database
- Removed `HttpThreat` category

### CODE REVIEW

**Review by msk — COMMENTED** [review]
The move of `EventCategory` looks good overall, and I appreciate that you've kept the `derive`s minimal as we discussed.

I notice you've implemented `From<u8>` for `EventCategory`. While this might be useful in some contexts, I'm not sure why it's necessary in the protocol crate. Could you explain how you expect this to be used by clients of REview?

**Comment by syncpark** [comment]
> I notice you've implemented `From<u8>` for `EventCategory`. While this might be useful in some contexts, I'm not sure why it's necessary in the protocol crate. Could you explain how you expect this to be used by clients of REview?

I've tested review-database and review-web with the modified review-protocol and found review-web code use the `TryFrom` for `u8` type.

https://github.com/aicers/review-web/blob/de634210cd2e49689515fa59301df381d7ddbacc/src/graphql/event.rs#L802
```rust
        let mut categories = Vec::with_capacity(categories_input.len());
        for category in categories_input {
            categories.push(EventCategory::try_from(*category).map_err(|e| anyhow!(e))?);
        }
        Some(categories)
```

I implemented the trait instead of the use the `num_traits::FromPrimitive` or `num_derive::FromPrimitive`.

**Comment by msk** [comment]
Thank you for providing the context about the usage in review-web. After considering this, I have a few thoughts:

1. The `TryFrom<u8>` implementation, while useful for review-web, doesn't seem necessary for the protocol-level operations that review-protocol is intended to support. Our goal with review-protocol is to keep it minimal and focused on the essential definitions needed for the QUIC protocol between REview components.

2. Since this conversion is specific to review-web's needs, it would be more appropriate to implement it within the review-web crate itself. This allows us to maintain a cleaner separation of concerns between our crates.

3. Looking at the broader picture, it might be worth reconsidering why review-web is using numeric representations for the `EventCategory` in its GraphQL API. Using `enum` directly in the GraphQL schema could provide a more type-safe and self-documenting API, while also decoupling REview's GraphQL API from the specifics of its QUIC protocol.

Given these points, I suggest the following:

1. Remove the `From<u8>` implementation from the review-protocol crate.
2. If review-web needs this conversion, implement it locally within that crate.
3. (Optional) Consider refactoring review-web to use its own `enum EventCategory` directly in its GraphQL schema, rather than numeric values, and then defining `TryFrom<EventCategory>` for review-database's `EventCategory`.

What are your thoughts on this approach? It would help us keep review-protocol focused while still meeting the needs of our other components.

**Comment by syncpark** [comment]
I removed the `From<u8>` implementation. I think too it's better to use `enum EventCategory` directly in review-web.

**Review by msk — APPROVED** [review]

**Pull request merged**
